sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.minimum=80

sonar.sources=src/main/java
sonar.tests=src/test/java

# No tests yet → ignore coverage
sonar.coverage.exclusions=**/*

sonar.coverage.exclusions=src/test/**