spring.application.name=dictionary-api

spring.mongodb.uri= ${MONGODB_URI}

logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG


#redis configuration
#when type is not set, by default it will set in memory cache
spring.cache.type=redis
spring.data.redis.host= localhost
spring.data.redis.port= 6379
spring.cache.cache-names= words
spring.data.redis.timeout=3000ms
spring.cache.redis.time-to-live= 3600